- alias: Set Google Home Slider Position
  trigger:
    - platform: state
      entity_id: media_player.living_room
  condition:
    - condition: template
      value_template: "{{ not is_state_attr('media_player.living_room', 'volume_level', states('input_number.google_home') | int / 100) }}"
  action:
    - service: input_number.set_value
      entity_id: input_number.google_home
      data_template:
        value: "{{ trigger.to_state.attributes.volume_level | multiply(100) | int }}"

- alias: Set Google Home Volume
  trigger:
    - platform: state
      entity_id: input_number.google_home
  condition:
    - condition: template
      value_template: "{{ not is_state_attr('media_player.living_room', 'volume_level', states('input_number.google_home') | int / 100) }}"
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room
      data_template:
        volume_level: "{{ states('input_number.google_home') | int / 100 }}"
