homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.1745901 
  longitude: 4.5145658 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: CET 
  # Customization file
  customize: !include customize.yaml
  packages:
    management: !include commands.yaml

# Show links to resources in log and frontend
#introduction:
logger:
  default: error 

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #  api_password: !secret api_password 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

device_tracker:
  - platform: nmap_tracker
    track_new_devices: no
    hosts: 192.168.1.251

nest:
  client_id: !secret nest_client_id 
  client_secret: !secret nest_client_secret

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

  - platform: template
    sensors:
      lr_playing:
        friendly_name: "Now Playing"
        value_template: >-
          {% if is_state('media_player.living_room', 'playing') %}
            ' {{states.media_player.living_room.attributes.media_title}}<br /> By {{states.media_player.living_room.attributes.media_artist}} '  
          {% elif is_state('media_player.living_room', 'paused') %}
            ' {{states.media_player.living_room.attributes.media_title}}<br /> By {{states.media_player.living_room.attributes.media_artist}} '
          {% else %} 
            Idle 
          {% endif %} 
       
# Weather (darksky.io)
#
  -  platform: darksky
     api_key: !secret forecast_io_api_key
     update_interval: 300
     monitored_conditions:
       - summary
       - icon
       - nearest_storm_distance
       - precip_type
       - precip_intensity
       - precip_probability
       - temperature
       - apparent_temperature
       - dew_point
       - wind_speed
       - wind_bearing
       - cloud_cover
       - humidity
       - pressure
       - visibility
       - ozone
       - minutely_summary
       - hourly_summary
       - daily_summary

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

hue:
  bridges: 
    - host: 192.168.1.220

tradfri:
  host: 192.168.1.202
  allow_tradfri_groups: false

camera:
  - platform: generic
    still_image_url: >
      {% if is_state('media_player.living_room', 'playing') %}
        http://192.168.1.203:8123/api/media_player_proxy/media_player.living_room?token={{ states.media_player.living_room.attributes.token }}
      {% elif is_state('media_player.living_room', 'paused') %}
        http://192.168.1.203:8123/api/media_player_proxy/media_player.living_room?token={{ states.media_player.living_room.attributes.token }}
      {% else %} 
        https://png.icons8.com/ios/1600/google-play-music.png 
      {% endif %}

input_number:
  google_home: 
    name: Volume 
    min: 0
    max: 100
    step: 1

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
