homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: CET 
  # Customization file
  customize: !include customize.yaml
  packages:
    management: !include commands.yaml

weather:
  - platform: darksky
    api_key: !secret forecast_io_api_key
    mode: daily
  - platform: buienradar
    latitude: !secret lat 
    longitude: !secret long 
    forecast: true
# Show links to resources in log and frontend
#introduction:
logger:
  default: warning 
  logs:
    miio.device: warning 
    homeassistant.components.vacuum: warning 
    zigbee2mqtt_networkmap: debug

recorder:
  purge_keep_days: 1
  exclude:
    domains:
      - group
      - history_graph
      - media_player
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.xiaomi_map
# Enables the frontend
frontend:
  themes: !include themes.yaml

lovelace:
        #mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #  api_password: !secret api_password 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

notify:
  - name: Push_Bullet_Adam 
    platform: pushbullet
    api_key: !secret pb_key_adam

  - name: Telegram_notifier
    platform: telegram
    chat_id: !secret telegrambot_chat_id 
# Enables a map showing the location of tracked devices
telegram_bot:
  - platform: polling
    api_key: !secret telegrambot_api_key 
    allowed_chat_ids:
      - !secret telegrambot_chat_id
map:

device_tracker:
  - platform: unifi
    host: 192.168.1.152 
    username: !secret unifi_user 
    password: !secret unifi_pass
    ssid_filter:
      - 'TacoTruck'

nest:
  client_id: !secret nest_client_id 
  client_secret: !secret nest_client_secret

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_merge_list sensors
tts:
  - platform: google_translate
    service_name: google_say
google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret
  track_new_calendar: true
# Cloud
cloud:
  google_actions:
    filter:
      exclude_entities:
        - script.skip_forward
        - script.skip_backward
        - script.pause_playback
        - script.play_pause_playback
        - script.play_playback
        - script.reboot_pi
        - script.shutdown_pi
        - script.all_downstairs_off
        - group.all_automations
        - group.all_devices
        - group.all_scripts
        - climate.dining_room
        - group.nest_stats
        - group.pi_hole
        - group.xiaomi_sensors
        - group.all_vacuum_cleaners
        - input_boolean.vacuum_ran
        - input_boolean.occupancy
        - input_boolean.light_by_motion
        - input_boolean.fan_by_sensor
     
camera:
  - platform: generic
    still_image_url: >
      {% if is_state('media_player.downstairs_2', 'playing') %}
        http://192.168.1.152:8123/api/media_player_proxy/media_player.living_room?token={{ states.media_player.living_room.attributes.token }}
      {% elif is_state('media_player.downstairs_2', 'paused') %}
        http://192.168.1.152:8123/api/media_player_proxy/media_player.living_room?token={{ states.media_player.living_room.attributes.token }}
      {% else %} 
        https://png.icons8.com/ios/1600/google-play-music.png 
      {% endif %}
  - platform: ffmpeg
    name: Dafang 
    input: -rtsp_transport tcp -i rtsp://192.168.3.21:8554/unicast

  - platform: mjpeg
    name: Octoprint 
    mjpeg_url: http://192.168.3.29/webcam/?action=stream

#input_number:
#  google_home: 
#    name: Volume 
#    min: 0
#    max: 100
#    step: 1
  - platform: generic
    name: Vacuum Map
    still_image_url: http://192.168.1.152:3500/api/map/image
    content_type: image/png
    framerate: 1

input_boolean:
  light_by_motion:
    name: Motion sensor activated 
    initial: off
    icon: mdi:home 

  occupancy:
    name: Occupancy
    initial: on
    icon: mdi:home

  vacuum_ran:
    name: Vacuum Ran
    initial: off
   
  valet_mode:
    name: Valet Mode
    initial: off
    icon: mdi:home

  fan_by_sensor:
    name: Fan sensor activated
    initial: off

  front_light_override:
    name: Porch override
    initial: off
    icon: mdi:lightbulb
  
  home_delay:
    name: Home Delay
    initial: off

  mm_auto:
    name: Magic Mirror Auto Mode
    initial: on

  door_open:
    name: Living Room Door Open
    initial: off

  prusa_master:
    name: Prusa Master Switch
    initial: off

  thermostat_lock:
    name: Thermostat Lock
    initial: off

input_select:
#  house_fan_mode:
#    name: Fan Mode
#    options:
#      - "low"
#      - "medium"
#      - "high"
#    icon: mdi:fan

  house_fan_timer:
    name: Fan Timer
    options:
      - "Off" 
      - "10 Minutes"
      - "20 Minutes"
      - "30 Minutes"
    icon: mdi:clock

light:
  - platform: mqtt
    schema: json
    name: "Stair LEDs"
    state_topic: "homeassistant/light/stairs_LEDs"
    command_topic: "homeassistant/light/stairs_LEDs/set"
#    effect: true
#    effect_list:
#      - bpm
#      - candy cane  
#      - confetti  
#      - cyclon rainbow  
#      - dots  
#      - fire  
#      - glitter  
#      - juggle  
#      - lightning
#      - noise  
#      - police all  
#      - police one  
#      - rainbow  
#      - rainbow with glitter  
#      - ripple  
#      - sinelon  
#      - solid  
#      - twinkle  
    brightness: true
    rgb: true
    qos: 0
    optimistic: true 

  - platform: mqtt
    name: Kitchen Light
    state_topic: "zigbee2mqtt/Kitchen Light"
    availability_topic: "zigbee2mqtt/bridge/state"
    schema: json
    command_topic: "zigbee2mqtt/Kitchen Light/set"

  - platform: mqtt
    name: Livingroom Hanglamp
    state_topic: "zigbee2mqtt/Livingroom Hanglamp"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/Livingroom Hanglamp/set"

scene:
  - name: LED rainbow 
    entities: 
      light.kitchen_leds:
        state: on
        effect: rainbow
        brightness: 50
  - name: LED solid
    entities:
      light.kitchen_leds:
        state: on
        effect: solid
        brightness: 255 
        xy_color: [0.493, 0.389]
  - name: LED Police 
    entities:
      light.kitchen_leds:
        state: on
        effect: police all 
        brightness: 50
  - name: Movies 
    entities:
      light.corner:
        state: on
        brightness: 128 
        xy_color: [0.689,0.309]
      light.corner_2:
        state: on
        brightness: 128
        xy_color: [0.689,0.309]
      light.stairs_3:
        state: off
      light.dining_table:
        state: on
        brightness: 128
        xy_color: [0.689,0.309]
      light.kitchen_leds:
        state: on 
        brightness: 128
        xy_color: [0.689,0.309]

input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

binary_sensor:
  - platform: bayesian
    name: aggregate_occupancy
    prior: 0.6
    probability_threshold: 0.9
    observations:
     - entity_id: 'sensor.adam_phone_ground_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50
     - entity_id: 'sensor.adam_phone_first_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50
     - entity_id: 'sensor.adam_watch_ground_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50
     - entity_id: 'sensor.adam_watch_first_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50
     - entity_id: 'sensor.amy_phone_ground_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50
     - entity_id: 'sensor.amy_phone_first_floor'
       prob_given_true: 0.90
       prob_given_false: 0.1
       platform: 'numeric_state'
       above: 50

switch:
  - platform: mqtt
    name: MagicMirror Display
    state_topic: "home/magic_mirror"
    command_topic: "home/magic_mirror/set"
    #availability_topic: "home/magic_mirror/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    retain: true
  
  - platform: mqtt
    name: OctoPi 
    state_topic: "home/prusa"
    command_topic: "home/prusa/set"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"

panel_iframe:
#  configurator:
#    title: 'Configurator'
#    icon: 'mdi:wrench'
#    url: 'http://192.168.1.152:3218'

  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://192.168.1.152:1880/'
  
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

zigbee2mqtt_networkmap:

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: 192.168.3.9  # Remove if you want to use builtin-in MQTT broker
  port: 1883
  #birth_message:
  #  topic: 'hass/status'
  #  payload: 'online'
  #will_message:
  #  topic: 'hass/status'
  #  payload: 'offline'
  username: !secret mqtt_user
  password: !secret mqtt_pass 

vacuum:
  - platform: xiaomi_miio
    host: 192.168.3.23 
    token: !secret mi_vac_key

influxdb:
  host: 192.168.1.152
  include:
    entities:
      - sensor.bathroom_humidity
      - sensor.bathroom_temperature
      - climate.dining_room
      - sensor.dining_room_thermostat_humidity
      - sensor.dining_room_thermostat_hvac_state
      - sensor.dining_room_thermostat_operation_mode
      - sensor.dining_room_thermostat_target
      - sensor.dining_room_thermostat_temperature
      - sensor.adam_first_floor
      - sensor.amy_first_floor
      - sensor.adam_ground_floor
      - sensor.amy_ground_floor
      - sensor.home_occupancy_confidence_of_adam
      - sensor.home_occupancy_confidence_of_amy
      - sensor.fan_state
      - binary_sensor.dining_room_thermostat_fan
      - binary_sensor.dining_room_thermostat_has_leaf
      - binary_sensor.dining_room_thermostat_is_locked
      - binary_sensor.dining_room_thermostat_is_using_emergency_heat
      - binary_sensor.dining_room_thermostat_online
      - binary_sensor.front_door_contact
      - binary_sensor.kitchen_window_contact
      - binary_sensor.laundry_window_contact
      - binary_sensor.living_room_door_contact
      - binary_sensor.mi_motion_sensor_occupancy
      - binary_sensor.office_window_contact
      - sensor.kitchen_window_battery
      - sensor.laundry_window_battery
      - sensor.living_room_door_battery
      - sensor.front_door_battery
      - sensor.mi_motion_sensor_battery
      - sensor.office_window_battery
      - sensor.vacuum_battery
      - sensor.vacuum_status
      - vacuum.xiaomi_vacuum_cleaner
      - light.corner
      - light.corner_2
      - light.dining_table
      - light.front_door
      - light.guest_room_light
      - light.kitchen_leds
      - light.kitchen_light
      - light.living_room_3
      - light.master_bedroom_strip
      - light.stairs_3
      - switch.garden_lights
      - switch.magicmirror_display

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
